/**
 * Painted OBJ + MTL writer — merges per-part STLs into ONE material-annotated
 * Wavefront OBJ (each part is its own `g`/`usemtl` group) plus a companion
 * `.mtl` carrying a PBR material per part (base colour + roughness + metalness).
 *
 * This is the portable, material-bearing mesh deliverable the paint stage
 * emits. It complements the plain geometry-only `final.obj` (see obj.ts) — same
 * geometry, but split into coloured groups and normalized to the SAME unit
 * bbox so the two line up exactly.
 *
 * Why MTL: STL carries no colour, and OpenSCAD's `color()` is lost on STL
 * export. A grouped OBJ + MTL is the lowest-common-denominator way to ship
 * per-part appearance that Blender, three.js, Maya, etc. all read. We emit both
 * the classic phong fields (Kd/Ka/Ks/Ns) AND the PBR extensions (Pr/Pm/Ke) that
 * Blender's OBJ importer maps onto the Principled BSDF.
 */

import { writeFileSync } from "node:fs";
import { basename } from "node:path";

import { loadSTL, computeBBox, transformInPlace } from "./stl.ts";

export interface PaintedPart {
  /** Module name — becomes the OBJ group + MTL material name. */
  name: string;
  /** Per-part STL at its true assembled world position (from the SCAD split). */
  stlPath: string;
  /** Base colour, 0..1 RGB. */
  color: [number, number, number];
  /** PBR roughness, 0..1. */
  roughness: number;
  /** PBR metalness, 0..1. */
  metalness: number;
  /** Emission strength 0..1 (for emissive parts — LEDs, screens). Default 0. */
  emission?: number;
}

export interface WritePaintedOBJResult {
  objPath: string;
  mtlPath: string;
  /** Parts that contributed geometry (empty meshes are skipped). */
  partsWritten: number;
  /** The unit-normalization that was applied (for parity with final.obj). */
  scale: number;
  center: [number, number, number];
}

const PRECISION = 5;

/** Phong specular exponent from a 0..1 roughness — smoother ⇒ tighter highlight. */
function nsFromRoughness(roughness: number): number {
  const r = Math.min(1, Math.max(0, roughness));
  return Math.max(1, Math.round((1 - r) * (1 - r) * 900 + 1));
}

function fmt(x: number): string {
  return x.toFixed(PRECISION);
}

function clamp01(x: number): number {
  return Number.isFinite(x) ? Math.min(1, Math.max(0, x)) : 0;
}

/**
 * Merge the supplied per-part STLs into one normalized OBJ + MTL.
 *
 * All parts are loaded, their COMBINED bbox is centred and uniformly scaled so
 * the longest axis spans `[-targetHalfExtent, targetHalfExtent]` (identical to
 * `normalizeMeshInPlace`), then each part is written as its own group that
 * references a per-part material in the `.mtl`.
 */
export function writePaintedOBJ(args: {
  parts: PaintedPart[];
  objOut: string;
  mtlOut: string;
  /** Half-extent of the longest axis after normalize. Default 1.0 (unit bbox). */
  targetHalfExtent?: number;
}): WritePaintedOBJResult {
  const targetHalfExtent = args.targetHalfExtent ?? 1.0;

  // Load every part; drop ones that compiled to empty geometry.
  const loaded = args.parts
    .map((part) => {
      try {
        return { part, mesh: loadSTL(part.stlPath) };
      } catch {
        return null;
      }
    })
    .filter((x): x is { part: PaintedPart; mesh: ReturnType<typeof loadSTL> } =>
      x !== null && x.mesh.triCount > 0);

  if (loaded.length === 0) {
    throw new Error("writePaintedOBJ: no non-empty part meshes to write");
  }

  // Combined bbox over all parts → shared centre + uniform scale (matches
  // normalizeMeshInPlace so final_painted.obj aligns with final.obj).
  let minX = Infinity, minY = Infinity, minZ = Infinity;
  let maxX = -Infinity, maxY = -Infinity, maxZ = -Infinity;
  for (const { mesh } of loaded) {
    const bb = computeBBox(mesh);
    if (bb.min[0] < minX) minX = bb.min[0];
    if (bb.min[1] < minY) minY = bb.min[1];
    if (bb.min[2] < minZ) minZ = bb.min[2];
    if (bb.max[0] > maxX) maxX = bb.max[0];
    if (bb.max[1] > maxY) maxY = bb.max[1];
    if (bb.max[2] > maxZ) maxZ = bb.max[2];
  }
  const center: [number, number, number] = [
    (minX + maxX) * 0.5, (minY + maxY) * 0.5, (minZ + maxZ) * 0.5,
  ];
  const longest = Math.max(maxX - minX, maxY - minY, maxZ - minZ);
  if (!(longest > 0)) throw new Error("writePaintedOBJ: zero-size combined bbox");
  const scale = (2.0 * targetHalfExtent) / longest;
  for (const { mesh } of loaded) transformInPlace(mesh, center, scale);

  // ── MTL ──────────────────────────────────────────────────────────────────
  // Unique material names (module names are already SCAD-safe identifiers; we
  // only guard against an accidental duplicate after compile-skips).
  const matNames: string[] = [];
  const usedNames = new Set<string>();
  const mtlLines: string[] = [
    `# generated by procedura/src/mesh/obj-mtl.ts`,
    `# ${loaded.length} part material(s)`,
  ];
  for (const { part } of loaded) {
    let name = part.name || "part";
    while (usedNames.has(name)) name = `${name}_`;
    usedNames.add(name);
    matNames.push(name);

    const [r, g, b] = [clamp01(part.color[0]), clamp01(part.color[1]), clamp01(part.color[2])];
    const rough = clamp01(part.roughness);
    const metal = clamp01(part.metalness);
    const emis = clamp01(part.emission ?? 0);
    // Phong fields (Kd/Ka/Ks/Ns) for legacy viewers + PBR (Pr/Pm/Ke) for
    // Blender's Principled importer. Ks is dim for dielectrics, white-ish for
    // metals so legacy viewers still read a metallic highlight.
    const ks = metal > 0.5 ? 0.9 : 0.2;
    mtlLines.push(
      ``,
      `newmtl ${name}`,
      `Ka 0.000 0.000 0.000`,
      `Kd ${fmt(r)} ${fmt(g)} ${fmt(b)}`,
      `Ks ${fmt(ks)} ${fmt(ks)} ${fmt(ks)}`,
      `Ns ${nsFromRoughness(rough)}`,
      `Pr ${fmt(rough)}`,
      `Pm ${fmt(metal)}`,
      ...(emis > 0 ? [`Ke ${fmt(r * emis)} ${fmt(g * emis)} ${fmt(b * emis)}`] : []),
      `d 1.0`,
      `illum 2`,
    );
  }
  writeFileSync(args.mtlOut, mtlLines.join("\n") + "\n", "utf8");

  // ── OBJ ──────────────────────────────────────────────────────────────────
  const objLines: string[] = [
    `# generated by procedura/src/mesh/obj-mtl.ts`,
    `mtllib ${basename(args.mtlOut)}`,
    `o painted_model`,
  ];
  let baseIndex = 0; // running count of vertices already written (1-indexed OBJ)
  for (let pi = 0; pi < loaded.length; pi++) {
    const { mesh } = loaded[pi]!;
    const matName = matNames[pi]!;
    const dedup = new Map<string, number>(); // per-part vertex key → local 1-based idx
    const verts: number[] = [];
    const faces: number[] = [];
    const v = mesh.vertices;
    for (let i = 0; i < mesh.triCount; i++) {
      const vi = i * 9;
      const a = vertexIndex(dedup, verts, v[vi]!, v[vi + 1]!, v[vi + 2]!);
      const b = vertexIndex(dedup, verts, v[vi + 3]!, v[vi + 4]!, v[vi + 5]!);
      const c = vertexIndex(dedup, verts, v[vi + 6]!, v[vi + 7]!, v[vi + 8]!);
      faces.push(a, b, c);
    }
    objLines.push(`g ${matName}`, `usemtl ${matName}`);
    for (let i = 0; i < verts.length; i += 3) {
      objLines.push(`v ${fmt(verts[i]!)} ${fmt(verts[i + 1]!)} ${fmt(verts[i + 2]!)}`);
    }
    for (let i = 0; i < faces.length; i += 3) {
      objLines.push(`f ${baseIndex + faces[i]!} ${baseIndex + faces[i + 1]!} ${baseIndex + faces[i + 2]!}`);
    }
    baseIndex += verts.length / 3;
  }
  writeFileSync(args.objOut, objLines.join("\n") + "\n", "utf8");

  return {
    objPath: args.objOut,
    mtlPath: args.mtlOut,
    partsWritten: loaded.length,
    scale,
    center,
  };
}

function vertexIndex(
  dedup: Map<string, number>, verts: number[],
  x: number, y: number, z: number,
): number {
  const key = `${x.toFixed(PRECISION)}|${y.toFixed(PRECISION)}|${z.toFixed(PRECISION)}`;
  const cached = dedup.get(key);
  if (cached !== undefined) return cached;
  verts.push(x, y, z);
  const idx = verts.length / 3; // 1-indexed within this part
  dedup.set(key, idx);
  return idx;
}
